[providers]
providers = ["java"]

[variables]
NIXPACKS_JDK_VERSION = "17"
JAVA_OPTS = "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"

[start]
cmd = "java -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -jar target/appointment-booking-system-0.0.1-SNAPSHOT.jar --server.port=${PORT:-8080}"


